import prisma from '@/lib/db/prisma';

/**
 * Auto-sync bank statement for a given bank account and date.
 * Called automatically after payment verification or expense creation.
 * Regenerates the auto-generated entry for that specific transaction.
 */
export async function syncBankStatement(opts: {
  bankAccountId: number;
  date: Date;
  credit: number;
  debit: number;
  description: string;
  remark: string;
  transactionId: string;
  sourceType: string;
  sourceId: number;
  createdBy: number;
}) {
  const { bankAccountId, date, credit, debit, description, remark, transactionId, sourceType, sourceId, createdBy } = opts;

  // Check if entry already exists for this source — update it, else create
  const existing = await prisma.bankStatement.findFirst({
    where: { sourceType, sourceId, bankAccountId },
  });

  // Get running balance up to (not including) this entry
  const prevEntry = await prisma.bankStatement.findFirst({
    where: {
      bankAccountId,
      date: { lt: date },
      id: existing ? { not: existing.id } : undefined,
    },
    orderBy: [{ date: 'desc' }, { id: 'desc' }],
    select: { balance: true },
  });
  const prevBalance = (prevEntry as any)?.balance || 0;
  const newBalance = +(prevBalance + credit - debit).toFixed(2);

  if (existing) {
    await prisma.bankStatement.update({
      where: { id: existing.id },
      data: { date, creditAmount: credit, debitAmount: debit, balance: newBalance, description, remark, transactionId, isAutoGenerated: true },
    });
  } else {
    await prisma.bankStatement.create({
      data: { date, transactionId, creditAmount: credit, debitAmount: debit, balance: newBalance, bankAccountId, description, remark, sourceType, sourceId, isAutoGenerated: true, createdBy },
    });
  }

  // Recalculate all subsequent entries' running balance
  const subsequent = await prisma.bankStatement.findMany({
    where: { bankAccountId, date: { gte: date }, id: existing ? { not: existing.id } : undefined },
    orderBy: [{ date: 'asc' }, { id: 'asc' }],
  });

  let running = newBalance;
  for (const s of subsequent) {
    running = +(running + (s.creditAmount || 0) - (s.debitAmount || 0)).toFixed(2);
    await prisma.bankStatement.update({ where: { id: s.id }, data: { balance: running } });
  }
}