import prisma from '@/lib/db/prisma';

const toDay = (d: Date) =>
  new Date(d.getFullYear(), d.getMonth(), d.getDate(), 0, 0, 0, 0);

/**
 * Recalculate and persist the running balance for every bank-statement entry
 * for the given account starting from `fromDate` (day boundary, inclusive).
 *
 * Uses (date ASC, id ASC) as the canonical ordering so that multiple entries
 * on the same calendar day are sequenced by insertion order.
 */
export async function recalculateBalances(bankAccountId: number, fromDate: Date) {
  const prevEntry = await prisma.bankStatement.findFirst({
    where:   { bankAccountId, date: { lt: fromDate } },
    orderBy: [{ date: 'desc' }, { id: 'desc' }],
    select:  { balance: true },
  });

  let running: number;
  if (prevEntry) {
    running = prevEntry.balance;
  } else {
    const acct = await prisma.bankAccount.findUnique({
      where:  { id: bankAccountId },
      select: { openingBalance: true },
    });
    running = acct?.openingBalance ?? 0;
  }

  const entries = await prisma.bankStatement.findMany({
    where:   { bankAccountId, date: { gte: fromDate } },
    orderBy: [{ date: 'asc' }, { id: 'asc' }],
    select:  { id: true, creditAmount: true, debitAmount: true },
  });

  for (const e of entries) {
    running = +(running + (e.creditAmount ?? 0) - (e.debitAmount ?? 0)).toFixed(2);
    await prisma.bankStatement.update({ where: { id: e.id }, data: { balance: running } });
  }
}

/**
 * Remove the bank statement entry linked to a source record and recalculate
 * all subsequent balances.  Safe to call even if no entry exists (no-op).
 */
export async function removeBankStatement(opts: {
  sourceType: string;
  sourceId: number;
}) {
  const { sourceType, sourceId } = opts;

  const entry = await prisma.bankStatement.findFirst({
    where:  { sourceType, sourceId },
    select: { id: true, bankAccountId: true, date: true },
  });
  if (!entry) return;

  const recalcFrom = toDay(entry.date);
  await prisma.bankStatement.delete({ where: { id: entry.id } });
  await recalculateBalances(entry.bankAccountId, recalcFrom);
}

/**
 * Auto-sync a bank statement entry when a payment is verified or an expense is
 * created / updated.  Upserts the entry then recalculates all balances from the
 * earliest affected day onwards so same-day ordering is always respected.
 *
 * Handles bank-account changes: if the source was previously linked to a
 * different bank account the old entry is removed and that account is
 * re-balanced before the new entry is created.
 */
export async function syncBankStatement(opts: {
  bankAccountId: number;
  date: Date;
  credit: number;
  debit: number;
  description: string;
  remark: string;
  transactionId: string;
  sourceType: string;   // 'manual' | 'payment_trader' | 'payment_company' | 'expense'
  sourceId: number;
  createdBy: number;
}) {
  const {
    bankAccountId, date, credit, debit,
    description, remark, transactionId,
    sourceType, sourceId, createdBy,
  } = opts;

  const entryDate = toDay(date);

  // Find any existing entry for this source — intentionally ignores bankAccountId
  // so we detect and handle the case where the linked account changed.
  const existing = await prisma.bankStatement.findFirst({
    where:  { sourceType, sourceId },
    select: { id: true, date: true, bankAccountId: true },
  });

  // If the entry moved to a different bank account, clean up the old one first.
  if (existing && existing.bankAccountId !== bankAccountId) {
    const oldFrom = toDay(existing.date);
    await prisma.bankStatement.delete({ where: { id: existing.id } });
    await recalculateBalances(existing.bankAccountId, oldFrom);

    // Create fresh entry on the new account and recalculate.
    await prisma.bankStatement.create({
      data: {
        date: entryDate, transactionId, creditAmount: credit, debitAmount: debit,
        balance: 0, bankAccountId, description, remark,
        sourceType, sourceId, isAutoGenerated: true, createdBy,
      },
    });
    await recalculateBalances(bankAccountId, entryDate);
    return;
  }

  // If the entry is being moved to a later date on the same account we must
  // recalculate from its original date so the gap it leaves behind is corrected.
  const recalcFrom =
    existing && existing.date < entryDate ? toDay(existing.date) : entryDate;

  if (existing) {
    await prisma.bankStatement.update({
      where: { id: existing.id },
      data: {
        date: entryDate, creditAmount: credit, debitAmount: debit,
        description, remark, transactionId, isAutoGenerated: true,
      },
    });
  } else {
    await prisma.bankStatement.create({
      data: {
        date: entryDate, transactionId, creditAmount: credit, debitAmount: debit,
        balance: 0, bankAccountId, description, remark,
        sourceType, sourceId, isAutoGenerated: true, createdBy,
      },
    });
  }

  await recalculateBalances(bankAccountId, recalcFrom);
}
