import prisma from '@/lib/db/prisma';

/**
 * Auto-sync a bank statement entry when a payment is verified or expense is created.
 * Finds existing entry for this source or creates a new one,
 * then cascades the running balance to all subsequent entries.
 */
export async function syncBankStatement(opts: {
  bankAccountId: number;
  date: Date;
  credit: number;
  debit: number;
  description: string;
  remark: string;
  transactionId: string;
  sourceType: string;   // 'manual' | 'payment_trader' | 'payment_company' | 'expense'
  sourceId: number;
  createdBy: number;
}) {
  const {
    bankAccountId, date, credit, debit,
    description, remark, transactionId,
    sourceType, sourceId, createdBy,
  } = opts;

  // Upsert: update existing or create new entry for this source
  const existing = await prisma.bankStatement.findFirst({
    where: { sourceType, sourceId, bankAccountId },
  });

  // Balance of last entry strictly before this entry's date
  const prevEntry = await prisma.bankStatement.findFirst({
    where: {
      bankAccountId,
      date:        { lt: date },
      ...(existing ? { id: { not: existing.id } } : {}),
    },
    orderBy: [{ date: 'desc' }, { id: 'desc' }],
    select:  { balance: true },
  });
  const prevBalance = prevEntry?.balance ?? 0;
  const newBalance  = +(prevBalance + credit - debit).toFixed(2);

  let savedId: number;

  if (existing) {
    await prisma.bankStatement.update({
      where: { id: existing.id },
      data: {
        date, creditAmount: credit, debitAmount: debit,
        balance: newBalance, description, remark, transactionId,
        isAutoGenerated: true,
      },
    });
    savedId = existing.id;
  } else {
    const created = await prisma.bankStatement.create({
      data: {
        date, transactionId, creditAmount: credit, debitAmount: debit,
        balance: newBalance, bankAccountId, description, remark,
        sourceType, sourceId, isAutoGenerated: true, createdBy,
      },
    });
    savedId = created.id;
  }

  // Cascade: recalculate all entries AFTER this one (exclude the saved entry itself)
  const subsequent = await prisma.bankStatement.findMany({
    where: {
      bankAccountId,
      date: { gte: date },
      id: { not: savedId },
    },
    orderBy: [{ date: 'asc' }, { id: 'asc' }],
    select: { id: true, creditAmount: true, debitAmount: true },
  });

  let running = newBalance;
  for (const s of subsequent) {
    running = +(running + (s.creditAmount ?? 0) - (s.debitAmount ?? 0)).toFixed(2);
    await prisma.bankStatement.update({ where: { id: s.id }, data: { balance: running } });
  }
}
