import { NextRequest, NextResponse } from 'next/server';
import prisma from '@/lib/db/prisma';
import { requireAuth } from '@/lib/auth/middleware';
import { recalculateBalances } from '@/lib/bank-statement-sync';

// ── helpers ───────────────────────────────────────────────────────────────────
const toDay    = (d: Date) => new Date(d.getFullYear(), d.getMonth(), d.getDate(), 0, 0, 0, 0);
const dayEnd   = (d: Date) => new Date(d.getFullYear(), d.getMonth(), d.getDate(), 23, 59, 59, 999);

function buildDateFilter(sp: URLSearchParams): { dateWhere: any; filterStart: Date | null } {
  const period = sp.get('period') || 'all';
  let dateWhere: any    = {};
  let filterStart: Date | null = null;

  if (period === 'month') {
    const month = parseInt(sp.get('month') || '0');
    const year  = parseInt(sp.get('year')  || '0');
    if (month && year) {
      filterStart = new Date(year, month - 1, 1);
      dateWhere   = { gte: filterStart, lte: new Date(year, month, 0, 23, 59, 59, 999) };
    }
  } else if (period === 'day') {
    const d = sp.get('date') ? new Date(sp.get('date')!) : null;
    if (d) {
      filterStart = toDay(d);
      dateWhere   = { gte: filterStart, lte: dayEnd(d) };
    }
  } else if (period === 'range') {
    const s = sp.get('start') ? new Date(sp.get('start')!) : null;
    const e = sp.get('end')   ? new Date(sp.get('end')!)   : null;
    if (s && e) {
      filterStart = toDay(s);
      dateWhere   = { gte: filterStart, lte: dayEnd(e) };
    }
  }

  return { dateWhere, filterStart };
}

function ser(s: any) {
  return {
    _id:             String(s.id),
    id:              s.id,
    date:            s.date?.toISOString?.() ?? s.date,
    description:     s.description   ?? '',
    remark:          s.remark        ?? '',
    transactionId:   s.transactionId ?? '',
    sourceType:      s.sourceType    ?? 'manual',
    creditAmount:    s.creditAmount  ?? 0,
    debitAmount:     s.debitAmount   ?? 0,
    balance:         s.balance       ?? 0,
    isAutoGenerated: s.isAutoGenerated ?? false,
    bankAccount: s.bankAccount
      ? { _id: String(s.bankAccount.id), bankName: s.bankAccount.bankName, accountNumber: s.bankAccount.accountNumber }
      : null,
  };
}

// ── GET /api/bank-statements ──────────────────────────────────────────────────
export async function GET(req: NextRequest) {
  const { error } = await requireAuth(['admin', 'accountant']);
  if (error) return error;

  const sp            = req.nextUrl.searchParams;
  const bankAccountId = sp.get('bankAccount') ? parseInt(sp.get('bankAccount')!) : null;
  const { dateWhere, filterStart } = buildDateFilter(sp);

  const where: any = {};
  if (bankAccountId) where.bankAccountId = bankAccountId;
  if (Object.keys(dateWhere).length) where.date = dateWhere;

  try {
    const statements = await prisma.bankStatement.findMany({
      where,
      orderBy: [{ date: 'asc' }, { id: 'asc' }],
      include: { bankAccount: { select: { id: true, bankName: true, accountNumber: true } } },
    });

    // Opening balance: last entry strictly before filter start
    let openingBalance: number | null = null;
    if (bankAccountId) {
      // Use the account's immutable openingBalance as the ultimate fallback
      const acct = await prisma.bankAccount.findUnique({
        where:  { id: bankAccountId },
        select: { openingBalance: true },
      });
      const accountOpeningBal = acct?.openingBalance ?? 0;

      if (filterStart) {
        const prev = await prisma.bankStatement.findFirst({
          where:   { bankAccountId, date: { lt: filterStart } },
          orderBy: [{ date: 'desc' }, { id: 'desc' }],
          select:  { balance: true },
        });
        openingBalance = prev?.balance ?? accountOpeningBal;
      } else {
        // period = 'all': only expose opening balance when there are no statements
        // (otherwise the first statement's balance already includes it)
        const firstEntry = await prisma.bankStatement.findFirst({
          where:   { bankAccountId },
          orderBy: [{ date: 'asc' }, { id: 'asc' }],
          select:  { id: true },
        });
        if (!firstEntry && accountOpeningBal !== 0) {
          openingBalance = accountOpeningBal;
        }
      }
    }

    const data = statements.map(ser);
    return NextResponse.json({
      statements:     data,
      openingBalance,
      closingBalance: data.length > 0 ? data[data.length - 1].balance : (openingBalance ?? 0),
      totalCredit:    data.reduce((s, x) => s + x.creditAmount, 0),
      totalDebit:     data.reduce((s, x) => s + x.debitAmount,  0),
    });
  } catch (err: any) {
    console.error('GET /api/bank-statements:', err.message);
    return NextResponse.json({ statements: [], openingBalance: null, error: err.message }, { status: 500 });
  }
}

// ── POST /api/bank-statements (manual entry — accountant only) ────────────────
export async function POST(req: NextRequest) {
  const { error, session } = await requireAuth(['accountant']);
  if (error) return error;

  try {
    const body = await req.json();
    const { date, transactionId, creditAmount, debitAmount, bankAccount, description, remark } = body;

    if (!bankAccount)         return NextResponse.json({ error: 'Bank account is required' }, { status: 400 });
    if (!description?.trim()) return NextResponse.json({ error: 'Description is required' },   { status: 400 });

    const credit = parseFloat(creditAmount || '0') || 0;
    const debit  = parseFloat(debitAmount  || '0') || 0;
    if (credit === 0 && debit === 0)
      return NextResponse.json({ error: 'Enter a credit or debit amount' }, { status: 400 });

    const bId       = parseInt(String(bankAccount));
    const entryDate = date ? new Date(date) : new Date();
    const dayStart  = toDay(entryDate);

    // Create the entry with a placeholder balance — recalculateBalances will set it correctly
    const statement = await prisma.bankStatement.create({
      data: {
        date:            dayStart,
        transactionId:   transactionId || '',
        creditAmount:    credit,
        debitAmount:     debit,
        balance:         0,
        bankAccountId:   bId,
        description:     description.trim(),
        remark:          remark || '',
        sourceType:      'manual',
        isAutoGenerated: false,
        createdBy:       parseInt((session!.user as any).id),
      },
      include: { bankAccount: { select: { id: true, bankName: true, accountNumber: true } } },
    });

    // Recalculate every entry from this day onwards.
    // This correctly handles same-day ordering by (date, id) and cascades all future entries.
    await recalculateBalances(bId, dayStart);

    // Re-fetch the statement so the response contains the correct updated balance
    const updated = await prisma.bankStatement.findUnique({
      where:   { id: statement.id },
      include: { bankAccount: { select: { id: true, bankName: true, accountNumber: true } } },
    });

    return NextResponse.json({ statement: ser(updated) }, { status: 201 });
  } catch (err: any) {
    console.error('POST /api/bank-statements:', err.message);
    return NextResponse.json({ error: err.message || 'Failed to create entry' }, { status: 500 });
  }
}
