import { NextRequest, NextResponse } from 'next/server';
import prisma from '@/lib/db/prisma';
import { requireAuth } from '@/lib/auth/middleware';

export async function POST(req: NextRequest) {
  const { error, session } = await requireAuth(['admin', 'accountant']);
  if (error) return error;

  const { bankAccountId, month, year } = await req.json();
  if (!bankAccountId || !month || !year)
    return NextResponse.json({ error: 'bankAccountId, month and year are required' }, { status: 400 });

  const userId = parseInt((session!.user as any).id);
  const bId    = parseInt(String(bankAccountId));
  const start  = new Date(year, month - 1, 1);
  const end    = new Date(year, month, 0, 23, 59, 59, 999);

  // Delete previous auto-generated entries for this account + month
  await prisma.bankStatement.deleteMany({
    where: { bankAccountId: bId, isAutoGenerated: true, date: { gte: start, lte: end } },
  });

  type Entry = {
    date: Date; credit: number; debit: number;
    description: string; remark: string;
    transactionId: string; sourceType: string; sourceId: number;
  };
  const entries: Entry[] = [];

  // ── 1. Verified TRADER payments → CREDIT ────────────────────────────────
  const traderPayments = await prisma.payment.findMany({
    where: {
      status: 'verified', paymentFor: 'trader',
      bankAccountId: bId,
      date: { gte: start, lte: end },
    },
    include: { trader: { select: { name: true } } },
    orderBy: { date: 'asc' },
  });
  for (const p of traderPayments) {
    entries.push({
      date:          p.date,
      credit:        p.amount,
      debit:         0,
      description:   `Payment received from ${p.trader?.name ?? 'Trader'}`,
      remark:        `Trader: ${p.trader?.name ?? '—'} | ${p.paymentMethod ?? 'N/A'}`,
      transactionId: p.utrNumber || p.chequeNumber || p.transactionId || '',
      sourceType:    'payment_trader',
      sourceId:      p.id,
    });
  }

  // ── 2. Verified COMPANY payments → DEBIT ────────────────────────────────
  const companyPayments = await prisma.payment.findMany({
    where: {
      status: 'verified', paymentFor: 'company',
      bankAccountId: bId,
      date: { gte: start, lte: end },
    },
    include: { company: { select: { name: true } } },
    orderBy: { date: 'asc' },
  });
  for (const p of companyPayments) {
    entries.push({
      date:          p.date,
      credit:        0,
      debit:         p.amount,
      description:   `Payment made to ${p.company?.name ?? 'Company'}`,
      remark:        `Company: ${p.company?.name ?? '—'} | ${p.paymentMethod ?? 'N/A'}`,
      transactionId: p.utrNumber || p.chequeNumber || p.transactionId || '',
      sourceType:    'payment_company',
      sourceId:      p.id,
    });
  }

  // ── 3. Expenses → DEBIT ─────────────────────────────────────────────────
  const expenses = await prisma.expense.findMany({
    where: { bankAccountId: bId, date: { gte: start, lte: end } },
    orderBy: { date: 'asc' },
  });
  for (const e of expenses) {
    entries.push({
      date:          e.date,
      credit:        0,
      debit:         e.amount,
      description:   `Expense: ${e.expenseType}`,
      remark:        `${e.expenseType} | ${e.paymentMethod}`,
      transactionId: e.transactionId || '',
      sourceType:    'expense',
      sourceId:      e.id,
    });
  }

  // Sort chronologically
  entries.sort((a, b) => a.date.getTime() - b.date.getTime());

  // Opening balance = last entry before this period
  const prev = await prisma.bankStatement.findFirst({
    where:   { bankAccountId: bId, date: { lt: start } },
    orderBy: [{ date: 'desc' }, { createdAt: 'desc' }],
    select:  { balance: true },
  });
  let running = prev?.balance ?? 0;

  // Create entries
  const created = [];
  for (const e of entries) {
    running = +(running + e.credit - e.debit).toFixed(2);
    const stmt = await prisma.bankStatement.create({
      data: {
        date: e.date, transactionId: e.transactionId,
        creditAmount: e.credit, debitAmount: e.debit, balance: running,
        bankAccountId: bId, description: e.description, remark: e.remark,
        sourceType: e.sourceType, sourceId: e.sourceId,
        isAutoGenerated: true, createdBy: userId,
      },
    });
    created.push(stmt);
  }

  // Recalculate ALL entries from period start onward (auto-generated + manual) to fix any gaps
  const allFromStart = await prisma.bankStatement.findMany({
    where:   { bankAccountId: bId, date: { gte: start } },
    orderBy: [{ date: 'asc' }, { createdAt: 'asc' }],
    select:  { id: true, creditAmount: true, debitAmount: true },
  });
  let cascadeRunning = prev?.balance ?? 0;
  for (const s of allFromStart) {
    cascadeRunning = +(cascadeRunning + (s.creditAmount ?? 0) - (s.debitAmount ?? 0)).toFixed(2);
    await prisma.bankStatement.update({ where: { id: s.id }, data: { balance: cascadeRunning } });
  }

  const label = start.toLocaleDateString('en-IN', { month: 'long', year: 'numeric' });
  return NextResponse.json({ message: `Generated ${created.length} entries for ${label}`, count: created.length });
}
