// ─── Bank Statement Types ─────────────────────────────────────────────────────
// Single source of truth for all bank-statement shapes used by API routes,
// service functions, and frontend components.

export type SourceType =
  | 'manual'
  | 'opening_balance'
  | 'payment_trader'
  | 'payment_company'
  | 'expense';

export type PeriodType = 'all' | 'day' | 'month' | 'range';

// ── API response shapes ────────────────────────────────────────────────────────

export interface BankStatementRow {
  _id:             string;
  id:              number;
  date:            string;          // ISO 8601
  description:     string;
  remark:          string;
  transactionId:   string;
  sourceType:      SourceType;
  creditAmount:    number;
  debitAmount:     number;
  balance:         number;
  isAutoGenerated: boolean;
  bankAccount: {
    _id:           string;
    bankName:      string;
    accountNumber: string;
  } | null;
}

export interface BankStatementListResponse {
  statements:     BankStatementRow[];
  openingBalance: number | null;
  closingBalance: number;
  totalCredit:    number;
  totalDebit:     number;
}

export interface GenerateStatementResponse {
  message: string;
  count:   number;
}

// ── Date filter ────────────────────────────────────────────────────────────────

export interface DateFilter {
  dateWhere:   { gte?: Date; lte?: Date };
  filterStart: Date | null;
}

// ── Manual entry form (accountant POST body) ───────────────────────────────────

export interface ManualEntryPayload {
  bankAccount:   string | number;
  date?:         string;
  description:   string;
  remark?:       string;
  transactionId?: string;
  creditAmount?: string | number;
  debitAmount?:  string | number;
}
